version: '3'

services:
  db:
    image: mysql:8.0.33
    container_name: MYSQL_DOCKER
    ports:
      - "3307:3306"  
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mobility_sharing_docker"
    volumes:
      - C:/Users/raule/Desktop/TFG/BACKEND/mobility-sharing/mobility-sharing/bd/mobility_sharing_docker:/var/lib/mysql
